name: Run the scraper

on:
 schedule:
    - cron: "*/5 * * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: deploy
          
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        ref: deploy

    - name: Run
      run: go run cmd/scraper/main.go